### ISSUE TITLE
希望优化第四个小码眼，以得到更完美的融合效果

### ISSUE THREAD

**Issue by idesign2018** [antfu/sd-webui-qrcode-toolkit#1]
### Clear and concise description of the problem

可以将第四个小码眼再次优化

### Suggested solution

第四个小码眼和其他三个大码眼一样，也可以遵循极端“十字”方式，同样可以扫描，大致效果如下：
![image](https://github.com/antfu/sd-webui-qrcode-toolkit/assets/42263070/697ffc6e-908e-4414-a0a1-4a28ddc94198)
也可以有更多变体：
![image](https://github.com/antfu/sd-webui-qrcode-toolkit/assets/42263070/bd9c0b2c-35bb-4b19-88b3-f8cd7df834c4)
![image](https://github.com/antfu/sd-webui-qrcode-toolkit/assets/42263070/bb4ea9b3-c1d5-4519-893c-70a40acceaee)
这样，在生成二维码的时候，可以得到更好的隐藏和画面更好的融合

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Supported
