### ISSUE TITLE
这个能提供API接口供调用吗

### ISSUE THREAD

**Issue by zshaobo** [antfu/sd-webui-qrcode-toolkit#5]
### Clear and concise description of the problem

我想使用这个进行批量的二维码生成。需要使用api编写脚本进行使用。但是现在不知道怎么调用

### Suggested solution

提供API接口供调用

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
这是一个纯前端的项目，不会有 API。这里有个粗糙的批量下载入口 https://qrcode.antfu.me/batch 代码是开源的，有需要可以自行 fork 修改

**Comment by Lx15** [comment]
如果能有个npm包能调用就再好不过了，哈哈哈哈
