### ISSUE TITLE
when can qrcode-toolkit for comfyui come out ?much thanks

### ISSUE THREAD

**Issue by huzhongyyuan** [antfu/sd-webui-qrcode-toolkit#9]
### Clear and concise description of the problem

when can qrcode-toolkit for comfyui come out ?much thanks!

### Suggested solution

when can qrcode-toolkit for comfyui come out ?much thanks!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
I don't use comfyui myself, but it shouldn't hard to embed an iframe for that. You have this repo as a reference to see how you can implement it.
